#!/usr/bin/env bash

# Update package list and install Apache
apt-get update
apt-get install -y nginx 

# Create the HTML file with "Hello Holberton"
echo "Hello Holberton" > /var/www/html/index.html

# Start Apache service
service nginx start
